# Generated by Django 3.2.1 on 2021-09-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityIntermediateExchange',
            fields=[
                ('variable_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('input_group', models.CharField(blank=True, max_length=10, null=True)),
                ('output_group', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'activity_intermediate_exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestActivityIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_index_id', models.CharField(max_length=36)),
                ('geography_id', models.CharField(max_length=1000)),
                ('start_date', models.CharField(max_length=1000)),
                ('end_date', models.CharField(max_length=1000)),
                ('special_activity_type', models.CharField(max_length=1000)),
                ('system_model_id', models.CharField(max_length=1000)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestIdName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestVersionNameIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_index_id', models.CharField(max_length=36)),
                ('activity_name_id', models.CharField(max_length=1000)),
                ('version_id', models.CharField(max_length=1000)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AcitivityIntermediateExchange',
        ),
    ]
