# Generated by Django 3.2.7 on 2022-03-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntiApp', '0003_document_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('differences', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'correspondence',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(blank=True, upload_to='uploaded_files/'),
        ),
    ]
