# Generated by Django 3.2.1 on 2022-03-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntiApp', '0003_document_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(blank=True, upload_to='uploaded_files/'),
        ),
    ]
