# Generated by Django 3.2.1 on 2022-03-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntiApp', '0004_auto_20220307_0905'),
        ('IntiApp', '0004_auto_20220309_0715'),
    ]

    operations = [
    ]
